### ISSUE TITLE
Combining with `thenify`

### ISSUE THREAD

**Issue by ruimarinho** [thenables/callback-and-promise#2]
What do you think of merging (or combining) `thenify` with this package? The only difference is that `thenify` does not accept a callback and `yield`/`await` would not work if a callback is passed, as expected.

**Comment by dead-horse** [comment]
This package's target is to help people who want to write library both support callback style and promise style. but `thenify`'s target is to turn callback style into promise style in the userland. `callback-and-promise` mostly used by the owner of libraries, so they could know the side-effect, but `thenify` mostly used by the users, the issue in https://github.com/thenables/callback-and-promise/pull/1#issuecomment-67970906 will make them confused.

**Comment by ruimarinho** [comment]
Yes, I understand that. My concern is that this library uses most of `thenify`'s code, which might confuse people on which one to use, even though they have different purposes. There may be also optimisations that benefit one or another library. What if `callback-and-promise` uses `thenify` with an option to enable callbacks too? Then `callback-and-promise` would become something like:

```js
module.exports = require('thenify')({ callback: true });
```

**Comment by dead-horse** [comment]
cc @jonathanong, what do you think?

or something like: 
```js
var thenify = require('thenify/withcallback');
```

**Comment by ruimarinho** [comment]
I prefer that option too!

**Comment by jonathanong** [comment]
Sure why not

**Comment by ruimarinho** [comment]
@jonathanong closing this as all changes have been applied. What do you think about adding a "DEPRECATED - " prefix on the repo's description?
